version: 2
jobs:
  build_10.15.3:
    docker:
      - image: 'circleci/node:10.15.3'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-10-{{ checksum "package.json" }}'
            - v1-dependencies-10
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-10-{{ checksum "package.json" }}'
      - run: npm test
  build_12.6.0:
    docker:
      - image: 'circleci/node:12.6.0'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: npm rebuild
      - run: npm test
workflows:
  version: 2
  workflow:
    jobs:
      - build_10.15.3
      - build_12.6.0
